In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf 

# Intro to Deep Learning
## Live Demos

In [3]:
from tensorflow.python.client import device_lib

In [4]:
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 79338338217076736, name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 11467078509574381637
 physical_device_desc: "device: XLA_CPU device", name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 4159557610658150768
 physical_device_desc: "device: XLA_GPU device"]

In [5]:
tf.__version__

'2.0.0'

In [6]:
first_param = tf.constant(2)
second_param = tf.constant(3)

In [7]:
# Old versions
# tf.enable_eager_execution()

In [8]:
first_param

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=2>

In [9]:
first_param.numpy()

2

In [10]:
tf.multiply(first_param,second_param)

<tf.Tensor: id=2, shape=(), dtype=int32, numpy=6>

In [11]:
# def compute(a,b):
#     return tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)),2)

# Operators are overloaded

def compute(a,b):
    return (2 * a + 3 * b) ** 2

In [12]:
compute(first_param,second_param).numpy()

169

In [13]:
compute(2, 3)

169

In [14]:
compute(2.0, 3.0)

169.0

In [15]:
compute(np.array([2]), np.array([3]))

array([169])

In [16]:
compute(np.array([2, 42, 18]), np.array([3, -5, 12]))

array([ 169, 4761, 5184])

In [17]:
compute(tf.constant(2), tf.constant(30))

<tf.Tensor: id=18, shape=(), dtype=int32, numpy=8836>

In [18]:
compute(tf.constant([2, 42, 18]), tf.constant([3, -5, 12]))

<tf.Tensor: id=27, shape=(3,), dtype=int32, numpy=array([ 169, 4761, 5184], dtype=int32)>

In [19]:
# Now all is accepted as tensorflow tensors
@tf.function
def compute_dec(a,b):
    return (2 * a + 3 * b) ** 2

In [20]:
compute_dec(first_param,second_param).numpy()

169

In [21]:
compute_dec(2, 3)

<tf.Tensor: id=47, shape=(), dtype=int32, numpy=169>

In [22]:
compute_dec(2.0, 3.0)

<tf.Tensor: id=48, shape=(), dtype=int32, numpy=169>

In [23]:
compute_dec(np.array([2]), np.array([3]))

<tf.Tensor: id=63, shape=(1,), dtype=int64, numpy=array([169])>

In [24]:
compute_dec(np.array([2, 42, 18]), np.array([3, -5, 12]))

<tf.Tensor: id=78, shape=(3,), dtype=int64, numpy=array([ 169, 4761, 5184])>

In [25]:
compute_dec(tf.constant(2), tf.constant(30))

<tf.Tensor: id=81, shape=(), dtype=int32, numpy=8836>

In [26]:
a1, b1 = tf.constant([2, 3, 4]), tf.constant([3, 4, 5])

In [27]:
tf.summary.trace_on(graph=True, profiler=True)

In [28]:
result = compute_dec(a1, b1)

In [29]:
print(result.numpy())

[169 324 529]


In [30]:
writer = tf.summary.create_file_writer(logdir = "logs")

In [31]:
with writer.as_default():
    tf.summary.trace_export(name = "compute_func", step = 0, profiler_outdir = "logs")